services: 
  login:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: crystal run src/login_backend.cr
    ports: 
      - 8080:8080
    depends_on:
      - psql
  psql: 
    container_name: psql
    image: postgres
    environment:
      POSTGRES_USER: <PG_USERNAME>
      POSTGRES_PASSWORD: <PG_PASSWORD>
    ports:
      - 5432:5432