server_config:
  host: localhost
  port: 8080
# Database URL configuration
db: 
  pg: 
    postgres_username: test_user
    postgres_password: test_password
    database_name: test_db
    host: localhost
    port: 5432